### ISSUE TITLE
Memory leak in node

### ISSUE THREAD

**Issue by sloosch** [slamdata/purescript-aff-bus#10]
Hi,

noticed that Aff-Bus is leaking slowly memory in a toy project i have. Here is a minimal working example which shows the leakage quite well (on my machine after 30sec 500MB and rising):
````purescript
loopy :: BusRW Unit -> Aff _ Unit
loopy bus = do
  _ <- Bus.read bus
  _ <- forkAff $ loopy bus
  Bus.write unit bus
  
main :: forall e. Eff _ Unit
main = launchAff_ $ do
  bus <- Bus.make
  _ <- forkAff $ loopy bus
  Bus.write unit bus
````
I have only tested this with node (v8.11.1) not in a browser.

After playing around a bit, i noticed that the problem seems to be the traverse with Either here https://github.com/slamdata/purescript-aff-bus/blob/master/src/Control/Monad/Aff/Bus.purs#L64

Replacing the traverse with pattern-matching seems to fix the problem e.g.
````purescript
attempt (takeVar cell) >>= case _ of
    Left _ -> pure unit
    Right res -> do ....
````
Can anyone confirm the leakage? Is this even a problem in Aff-Bus or is it Aff making problems?

**Comment by safareli** [comment]
@natefaubion might know if it's Aff related

**Comment by natefaubion** [comment]
Looping inside a traverse_ isn’t tail recursive (it’s equivalent to `fix \loop -> loop *> pure unit`) so it will continue to build continuations indefinitely. It’s unfortunately expected behavior.

**Comment by sloosch** [comment]
@safareli 
Unrelated to the issue but maybe also consider replacing `sequence_ (foldl (\xs a → putVar res a : xs) mempty vars)` with `traverse_ (putVar res) vars`? Building an intermediate list of Affs seems unnecessary.

**Comment by natefaubion** [comment]
@sloosch It builds an intermediate list so that they are run in the order they were added. Reads are cons'ed. If we used traverse_ it would be LIFO instead FIFO.
