### ISSUE TITLE
Buffering of messages

### ISSUE THREAD

**Issue by felixSchl** [slamdata/purescript-aff-bus#3]
I am building an analog to pipes-concurrency ([purescript-pipes-aff](https://github.com/felixSchl/purescript-pipes-aff)), and I am looking for a solution to buffer messages for the producer to read from. Currently bus just gives me a single message and I have to be fast not to miss it. I am wondering what would be involved (and if this would be the right place for this) to buffer a configurable amount of messages with configurable behavior. What I like and appreciate about purescript-aff-bus is the notable absence of FFI calls, leaving that entirely to the purescript-aff library and I think the buffer implementations could and should be implemented similarly. For reference, this is how it's implemented in haskell: https://github.com/Gabriel439/Haskell-Pipes-Concurrency-Library/blob/fccb359dbfb2988da83166d4e2bc6ff01dbe986d/src/Pipes/Concurrent.hs#L177-L198. Any input would be greatly appreciated.

**Comment by garyb** [comment]
I'm not sure how you could have a write buffer for a bus without it leaking - how would you know when to clear the buffer?

`AVar` already buffers writes if you have a single consumer, so maybe using that directly would work?

**Comment by felixSchl** [comment]
Yes I think you are right. Building on top of `Avar` directly is probably the way to go for the reason you mentioned. Thank you

**Comment by garyb** [comment]
Please post a message here when you get something working, I'd like to see what you come up with :)
