### ISSUE TITLE
Use an unmanaged fork to decouple inner loop

### ISSUE THREAD

**Issue by kRITZCREEK** [slamdata/purescript-aff-bus#7]
Comment on #6:

> This might need to be an unsafe fork (liftEff <<< launchAff) unless you want to let users to control the lifecycle of the loop with supervised.

**Comment by safareli** [comment]
@kRITZCREEK, @natefaubion

I guess the last PR #9 "fixed" this issue too, as [launchAff_ is used](https://github.com/slamdata/purescript-aff-bus/blob/master/src/Control/Monad/Aff/Bus.purs#L69) now, so this can be closed?

**Comment by kRITZCREEK** [comment]
I think so, yeah. Thanks!
